### ISSUE TITLE
RestClient gem has a security alert, gems need updating

### ISSUE THREAD

**Issue by skierkowski** [tutumcloud/ruby-tutum#19]
https://github.com/rest-client/rest-client/issues/369

**Comment by bfosberry** [comment]
I'll be out of town for the next few days, I may not be able to push out something till Monday, but I will make this a priority

**Comment by skierkowski** [comment]
Thanks.

If you do have the time before leaving town to merge the current PRs, I can make a PR for this update too. ATM it is blocked because tests are failing due to #12.
